version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cloudcommerce-postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./apps/product-service

    container_name: cloudcommerce-backend

    restart: always

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/products_db

    volumes:
      - ./apps/product-service:/app

  frontend:
    build:
      context: ./apps/frontend

    container_name: cloudcommerce-frontend

    restart: always

    depends_on:
      - backend

    ports:
      - "3000:3000"

    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000

    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data: