name: CloudCommerce 

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        working-directory: apps/frontend
        run: npm install

      - name: Build Frontend
        working-directory: apps/frontend
        run: npm run build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Backend Dependencies
        working-directory: apps/product-service
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Backend Docker Image
        run: docker build -t cloudcommerce-backend ./apps/product-service

      - name: Build Frontend Docker Image
        run: docker build -t cloudcommerce-frontend ./apps/frontend
